default: &default
  adapter: postgresql
  encoding: utf8
  username: postgres
  password: 1234
  pool: 5 # not mandatory
  timeout: 5000 # not mandatory
  host: 172.17.0.11
  port: 5432

development:
  <<: *default
  database: testProject

test:
  <<: *default
  database: testProject


production:
  <<: *default
  database: testProject
