# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 88fc67982e08fc12db1c882bf1faca08190b2e16358341fe9a7b69c9d1edbe6605e66a6f989a4b383f5f56c056727ca0ddfcbce8e01c55a1ff2adb11299da40b

test:
  secret_key_base: 092dffc22c1ca4e121035ce4f3165edd9115978b730e972b87701a1056f8cdf0ab1326130052582fc09baafcf9618e7a5cb1355ac2ad4a38c7f3dbd1d7ff8cea

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
